### ISSUE TITLE
Aggiungere ulteriori livelli di campione

### ISSUE THREAD

**Issue by zgruntolo** [codeclysm/fultimator#6]
Al momento è possibile arrivare solo ad un massimo di campione (4). Sarebbe interessante poter arrivare almeno a 5/6 per combattimenti difficili contro gruppi numerosi

**Comment by matteosuppo** [comment]
Ciao, ho deciso di fermarmi a campione 5 perché il gioco non si comporta bene con campioni troppo grossi. Prova invece ad aggiungere soldati od elite
