### ISSUE TITLE
Resistenza non contata nel totale delle abilità

### ISSUE THREAD

**Issue by MarcoRogic** [codeclysm/fultimator#7]
Ho generato un campione con 3 resistenze e due debolezze, provando ad inserire un'ulteriore resistenza essa non viene calcolata nel totale delle abilità
![image](https://user-images.githubusercontent.com/109983731/180840545-09334e30-8ac1-48d8-88bc-43d12cac740c.png)
![image](https://user-images.githubusercontent.com/109983731/180840572-7848c7a6-bd81-497b-bf3b-75494965908c.png)

**Comment by matteosuppo** [comment]
Ciao questo non è un bug perché una abilità si può usare per avere due resistenze
